dataset:
  h5: squad_dataset.1.1.2.h5
  max_sent_len: 30
  model_save_path: 'saved_models/model.pt'

scheduling:
  batch_size: 32
  valid_batch_size: 32
  epoch: 50
  enable_cuda: False
  cuda_seed: 42
  
optimizer:
  step_rule: 'adam'
  learning_rate: 0.001
  learning_rate_decay_ratio: 0.8
  learning_rate_decay_from_this_epoch: 2
  clip_grad_norm: 5

embedding:
  word_level:
    path: glove.840B.300d.txt.h5
    embedding_size: 300
    embedding_type: 'pretrained'
    embedding_trainable: False
    embedding_dropout: 0.3
    embedding_word_dropout: 0.
    embedding_oov_init: 'random'

  char_level:
    embedding_size: 32
    embedding_rnn_size: [32]
    embedding_trainable: True
    embedding_dropout: 0.3
    embedding_word_dropout: 0.

match_lstm:
  rnn_hidden_size: [256]
  match_lstm_hidden_size: [256]
  dropout_between_rnn_layers: 0.1
  dropout_between_rnn_hiddens: 0.1
  dropout_in_rnn_weights: 0.
  use_layernorm: False
  decoder_hidden_size: 128
